management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
feign:
  client:
    config:
      default:
        connectTimeout: 5000
      accountFeignClient:
        readTimeout: 10000    
resilience4j:
  circuitbreaker:
    instances:
      NotificationService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
resilience4j.timelimiter:
  instances:
    NotificationService:
      timeoutDuration: 2s
      cancelRunningFuture: true
resilience4j.retry:
    instances:
        NotificationService:
            maxAttempts : 5
            waitDuration: 10s
resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 2
      limitRefreshPeriod: 10s
      timeoutDuration: 0s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
  instances:
    NotificationService:
      baseConfig: default
      limitForPeriod: 5  
      